variable "vpc_cidr_block" {}
variable "subet_cidr_block" {}
variable "avail_zone" {}
variable "env_prefix" {}
variable "my_ip" {}
variable "ami_id" {}
variable "instance_type" {}
variable "public_key_location" {}
variable "private_key_location" {}